services:
    warkop_cakra:
        # container_name: node_warkop_cakra
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./:/app
            - /app/node_modules
            # - /app/.nextdocker -v
        ports:
            - 3001:3000
        # environment:
        #   - CHOKIDAR_USEPOLLING=true
